# NUMPY
                                                                                                            BY GULSHAN GEDAM

In [1]:
import numpy as np

## NumPy Array

In [2]:
l = [1,3,5,7,9]
np.array(l)

array([1, 3, 5, 7, 9])

In [3]:
l = [1,3,5,7,9]
npa = np.array(l)

In [4]:
type(l), type(npa)

(list, numpy.ndarray)

In [5]:
npa.shape

(5,)

In [6]:
l2 = [ 2,3, "string", 8,6]
l + l2

[1, 3, 5, 7, 9, 2, 3, 'string', 8, 6]

In [ ]:
l2 + 20 # --> ERROR

In [7]:
l2 + [20]

[2, 3, 'string', 8, 6, 20]

In [8]:
npa= np.array(l + l2)
npa

array(['1', '3', '5', '7', '9', '2', '3', 'string', '8', '6'],
      dtype='<U11')

In [10]:
l1 = [[2,3], [6,7], [8,9], [4,5]]
npa2d = np.array(l1)
npa2d

array([[2, 3],
       [6, 7],
       [8, 9],
       [4, 5]])

In [11]:
npa2d.shape

(4, 2)

In [12]:
npa2d = np.array(l1, dtype= 'float') #------>> Converting Data Type to FLOAT
npa2d

array([[2., 3.],
       [6., 7.],
       [8., 9.],
       [4., 5.]])

In [15]:
npa2d = npa2d.astype('int') # -- >> Converting Data Type to INT
npa2d

array([[2, 3],
       [6, 7],
       [8, 9],
       [4, 5]])

In [16]:
npa2d = npa2d.astype('str') # -- >> Converting Data Type to STRING
npa2d

array([['2', '3'],
       ['6', '7'],
       ['8', '9'],
       ['4', '5']], dtype='<U11')

In [17]:
npa2d[0][0], npa2d[1][1]

('2', '7')

## NAN and INF

In [ ]:
'''
NAN and INF 
NAN -> Not A Number
INF -> Infinity
'''

In [19]:
np.nan == np.nan # --> False


False

In [20]:
np.inf == np.inf

True

In [21]:
None == None

True

In [22]:
nan2d = np.array(l1)
nan2d

array([[2, 3],
       [6, 7],
       [8, 9],
       [4, 5]])

In [23]:
nan2d = nan2d.astype('float')
nan2d

array([[2., 3.],
       [6., 7.],
       [8., 9.],
       [4., 5.]])

In [25]:
nan2d[0][0] = np.nan
nan2d[1][1] = np.inf
nan2d

array([[nan,  3.],
       [ 6., inf],
       [ 8.,  9.],
       [ 4.,  5.]])

In [26]:
np.isnan(nan2d)

array([[ True, False],
       [False, False],
       [False, False],
       [False, False]])

In [27]:
np.isinf(nan2d)

array([[False, False],
       [False,  True],
       [False, False],
       [False, False]])

In [28]:
flag = np.isnan(nan2d) | np.isinf(nan2d)
flag

array([[ True, False],
       [False,  True],
       [False, False],
       [False, False]])

In [29]:
nan2d[flag]

array([nan, inf])

In [30]:
nan2d[flag] = 0
nan2d

array([[0., 3.],
       [6., 0.],
       [8., 9.],
       [4., 5.]])

## Statistical Operations

In [ ]:
'''
Statistical Operations
Mean Min Max Variance Median Standard-Daviance 
'''

In [31]:
print(nan2d.min())

0.0


In [32]:
nan2d.max()

9.0

In [33]:
nan2d.mean()

4.375

In [34]:
nan2d.std()

3.119995993587171

In [35]:
nan2d.var()

9.734375

In [36]:
np.median(nan2d)

4.5

## shape(), reshape(), ravel()

In [37]:
nan2d.shape

(4, 2)

In [38]:
nan2d

array([[0., 3.],
       [6., 0.],
       [8., 9.],
       [4., 5.]])

In [40]:
nan2d.reshape(2,4) #-->.Reshape the array / Change the

array([[0., 3., 6., 0.],
       [8., 9., 4., 5.]])

In [41]:
nan2d.reshape(1,8) #-->.Reshape the array / Change the

array([[0., 3., 6., 0., 8., 9., 4., 5.]])

In [42]:
nan2d.reshape(8,1)

array([[0.],
       [3.],
       [6.],
       [0.],
       [8.],
       [9.],
       [4.],
       [5.]])

In [ ]:
Remember the reshape value must be multiple of 8

nan2d.reshape(1,3)) --------->> This Gives Error


In [43]:
nan2d.reshape(1,8) 

array([[0., 3., 6., 0., 8., 9., 4., 5.]])

In [46]:
nan2d.reshape(8,1)

array([[0.],
       [3.],
       [6.],
       [0.],
       [8.],
       [9.],
       [4.],
       [5.]])

In [47]:
nan2d.reshape(1,8).ravel()

array([0., 3., 6., 0., 8., 9., 4., 5.])

In [49]:
nan2d.flatten()

array([0., 3., 6., 0., 8., 9., 4., 5.])

## Sequence, Repetition and Random Numbers 

In [ ]:
'''
Sequence, Repetition and Random Numbers

arange(), linspace(),random(), zeroes() and one()

PRINT EVERYTHING PRINT PRINT PRINT PRINT
'''

In [52]:
np.arange(1,5) # --> [1 2 3 4] -> 5 is Not Includes 

array([1, 2, 3, 4])

In [53]:
np.arange(1,5,dtype='float')

array([1., 2., 3., 4.])

In [54]:
np.arange(1,20,3) #-> Here 3 is step value 

array([ 1,  4,  7, 10, 13, 16, 19])

In [55]:
np.linspace(1, 20, 5)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [56]:
np.linspace(1, 20, 3)

array([ 1. , 10.5, 20. ])

In [57]:
np.logspace(1, 30, 10)

array([1.00000000e+01, 1.66810054e+04, 2.78255940e+07, 4.64158883e+10,
       7.74263683e+13, 1.29154967e+17, 2.15443469e+20, 3.59381366e+23,
       5.99484250e+26, 1.00000000e+30])

In [58]:
np.zeros([1,5])

array([[0., 0., 0., 0., 0.]])

In [59]:
np.zeros([1,3,2])

array([[[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [60]:
np.ones([1,3])

array([[1., 1., 1.]])

In [61]:
np.tile([1,2], 3)

array([1, 2, 1, 2, 1, 2])

In [62]:
np.repeat([1,2], 3)

array([1, 1, 1, 2, 2, 2])

In [63]:
np.random.rand(3,3)

array([[0.88722633, 0.59188994, 0.94155353],
       [0.94031793, 0.76021248, 0.36599387],
       [0.68507342, 0.95920944, 0.42858407]])

In [64]:
np.random.randint(1,10, [3,3]) #--> (seed(1) to stop random no. everytime)

array([[9, 8, 6],
       [4, 3, 2],
       [7, 7, 9]])

In [66]:
arr2D = [[3,4], [4,5], [6,5]]

arr = np.unique(arr2D)
arr

array([3, 4, 5, 6])

In [67]:
np.unique(arr2D, return_counts= True)

(array([3, 4, 5, 6]), array([1, 2, 2, 1], dtype=int64))

In [ ]:
'''
(array([3, 4, 5, 6]), array([1, 2, 2, 1], dtype=int64))
i.e means 3 -> 1 time, 4 and 5-> 2 times and 6 -> 1 time
'''

## Where

In [70]:
arr = np.array([23,5,67,8,5,19,34,6,90,87])
arr

array([23,  5, 67,  8,  5, 19, 34,  6, 90, 87])

In [71]:
(np.where(arr>20))
# This Gives Index Not Values, For values use below syntex

(array([0, 2, 6, 8, 9], dtype=int64),)

In [72]:
index = np.where(arr>20)
arr[index]

array([23, 67, 34, 90, 87])

In [73]:
index = np.where(arr < 10)
print(arr[index])

[5 8 5 6]


In [74]:
print(arr>10) # This gives result in boolean

[ True False  True False False  True  True False  True  True]


In [75]:
arr[arr>20] # Alternate of WHERE

array([23, 67, 34, 90, 87])

In [76]:
print(arr.max()) # This Gives Maximum Value, But what if we want index of Max No.

90


In [77]:
print(arr.argmax()) # This Gives Index of Max No.

8


In [78]:
print(arr.argmax()) # This Gives Index of Min No.

8


## Read and Write File 

In [79]:
arr2D = np.array([[3,4,8], [4,5,2], [6,5,3]])

In [80]:
np.savetxt('arr2D.csv', arr2D, delimiter=',')

In [81]:
np.loadtxt('arr2D.csv', delimiter=',')

array([[3., 4., 8.],
       [4., 5., 2.],
       [6., 5., 3.]])

In [82]:
np.save('data.npy', arr2D)

In [83]:
np.load('data.npy')

array([[3, 4, 8],
       [4, 5, 2],
       [6, 5, 3]])

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [84]:
np.savez('both.npz', arr, arr2D)

In [85]:
np.load('both.npz')

In [86]:
np.load('both.npz').files

['arr_0', 'arr_1']

In [87]:
d = np.load('both.npz')

In [88]:
d.files

['arr_0', 'arr_1']

In [89]:
d[d.files[0]] #----------->> For Opening 1st Array

array([23,  5, 67,  8,  5, 19, 34,  6, 90, 87])

In [90]:
d[d.files[1]] #----------->> For Opening 2st Array

array([[3, 4, 8],
       [4, 5, 2],
       [6, 5, 3]])

## CONCATENATE AND SORTING

In [91]:
arr2D = np.array([[3,4,8], [4,5,2], [6,5,3]])
arr = np.array([1,2,3,4,5,6,7])

In [92]:
con = np.concatenate([arr2D,arr2D], axis=0)
con

array([[3, 4, 8],
       [4, 5, 2],
       [6, 5, 3],
       [3, 4, 8],
       [4, 5, 2],
       [6, 5, 3]])

In [93]:
con = np.concatenate([arr2D,arr2D], axis=1)
con

array([[3, 4, 8, 3, 4, 8],
       [4, 5, 2, 4, 5, 2],
       [6, 5, 3, 6, 5, 3]])

In [ ]:
# con = np.concatenate([arr2D,arr], axis=1) # -->> This gives error 
# print(con) -->> Size of arr and arr2d are different

In [95]:
con = np.concatenate([arr,arr], axis=0)
con

array([1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7])

In [96]:
con1 = np.vstack([arr2D, arr2D])
con1

array([[3, 4, 8],
       [4, 5, 2],
       [6, 5, 3],
       [3, 4, 8],
       [4, 5, 2],
       [6, 5, 3]])

In [97]:
con = np.hstack([arr, arr])
con

array([1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7])

In [99]:
con1 = np.hstack([arr2D, arr2D])
con1.sort()
con1

array([[3, 3, 4, 4, 8, 8],
       [2, 2, 4, 4, 5, 5],
       [3, 3, 5, 5, 6, 6]])

## Dates

In [101]:
d = np.datetime64('2012-05-01 23:34:22')
print(d)

2012-05-01T23:34:22


In [102]:
print(d + 10) # -> 2012-05-01T23:34:32 This adds 10 Seconds in time

2012-05-01T23:34:32


In [103]:
one = np.timedelta64(1 , 'D')
print(d + one) # -> 2012-05-02T23:34:22 This adds 1 Day in time

2012-05-02T23:34:22


In [104]:
one = np.timedelta64( 21, 'm')
print(d + one)

2012-05-01T23:55:22
